# Generated by Django 4.0.4 on 2022-12-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time_to_work',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_memory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video_card',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
