version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  migration:
    image: marketplace
    command: bash -c "python manage.py makemigrations && python manage.py migrate && echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('test', 'admin@myproject.com', 'test')\" | python manage.py shell || python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/var/app/
    ports:
      - 8000:8000
    depends_on:
      - db
