# Generated by Django 3.2.7 on 2022-04-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tel'),
    ]

    operations = []
